### ISSUE TITLE
Proposal for initialization syntax

### ISSUE THREAD

**Issue by andrei-markeev** [YasserAsmi/jvar#17]
Hi,

Right now best we can get with jvar is something like this:
```cpp
jvar::Variant nestedData;
nestedData.createObject();
nestedData["p1"] = 10;
nestedData["p2"] = "test";

jvar::Variant data;
data.createObject();
data["prop1"] = "val1";
data["prop2"] = 1234;
data["prop3"] = nestedData;
```
Which is rather good, but still relatively awkward.

In JS, I would just write something like this:
```js
var data = {
  prop1: "val1",
  prop2: 1234,
  prop3: { p1: 10, p2: "test" }
}
```

It gets even worse when we're talking about arrays.
In JS, there's map-filter-reduce and it's not a problem to take an existing array and filter/transform it for sending over the wire without any problems. In C++03 it is many times more code and rather bulkier. But at least things can be improved in more recent versions of C++.

E.g. using C++11 I was able to come up with this kind of syntax:
```cpp
jvar::Variant data = v({
    { "prop1", "val1" },
    { "prop2", 1234 },
    { "prop3", v( { { "p1", 10 },  { "p2", "test" } } ) }
});
```
Which is not JS of course but so much better anyway!

This works with the following simple implementation of `v`:
```cpp
#include <initializer_list>

struct prop {
    const char *name;
    jvar::Variant val;
};

jvar::Variant v(std::initializer_list<const prop>&& props) {
    jvar::Variant obj;
    obj.createObject();

    for(const auto& p : props)
    {
        obj.addProperty(p.name, p.val);
    }

    return obj;
}
```

So my question is, what do you think of introducing some similar syntax in jvar? Of course, as a separate C++11 and up feature, enclosed in corresponding defines.

I can also try to produce arrays/vectors conversion.

P.S. Our project seems to be finally moving to C++11 and probably even further to C++14. All these lambda functions, variable type inferring with auto, list initializers - are very tempting and make C++ almost as modern language, at last! :)

**Comment by YasserAsmi** [comment]
Happy new year!

Sorry for the delay.  I was dealing with Mac build issues.  And issues with GCC5.0.  Apparently, gcc5 changes it's ABI for strings.   http://stackoverflow.com/questions/34571583/understanding-gcc-5s-glibcxx-use-cxx11-abi-or-the-new-abi/34578283#34578283  

This looks cool!  Most of my projects are C++11 now too.   I haven't mastered C++11 as much yet--but am aware of most features.  You had already added the C++11 option to jvar so the defines already exist.  Will you be making these changes?

**Comment by andrei-markeev** [comment]
Hi,

I added the PR, and in terms of syntax was able to achieve even better results, but haven't done much in terms of optimization.
I'm pretty sure it is possible to at least reserve memory beforehand when creating jvar objects and arrays. Right now it is allocated via addProperty/push on-the-go. I would appreciate if you reviewed the code and added necessary performance and memory allocation optimizations. Thanks!
