### ISSUE TITLE
incorrect parsing of empty string

### ISSUE THREAD

**Issue by lmcmgig** [YasserAsmi/jvar#18]
Hi,

  The stripQuotes function doesn't handle the empty string case correctly.
  Just one if to adjust:

void StrBld::stripQuotes(bool allowsingle)
{
[...]
        if ((c1 == '"' && c2 == '"') ||
            (allowsingle && c1 == '\'' && c2 == '\'') )
        {
            mLen--;

*****            if (mLen >= 1)     *****  instead of if (mLen > 1)
            {
                memmove(buf, buf + 1, mLen);
[...]
}

**Comment by YasserAsmi** [comment]
Fixed Thanks lmcmgig!
