### ISSUE TITLE
Mac OS X compilation error

### ISSUE THREAD

**Issue by dk547** [YasserAsmi/jvar#19]
Scanning dependencies of target jvar
[  8%] Building CXX object CMakeFiles/jvar.dir/src/str.cpp.o
[ 16%] Building CXX object CMakeFiles/jvar.dir/src/util.cpp.o
jvar-master/src/util.cpp:58:23: error: use of undeclared identifier 'CLOCK_MONOTONIC'
    if (clock_gettime(CLOCK_MONOTONIC, &ts))
                      ^
1 error generated.

It seems clock_gettime(CLOCK_MONOTONIC, &ts) is not implemented in mac os x

http://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x

**Comment by YasserAsmi** [comment]
dk547, thanks for reporting the issue.  I don't have a mac to test... but I believe following should work..  Will you be willing to try it out and let me know?  You can also simple disable the getTickCount() function as it is not used for anything critical--just for measuring elapsed time...

#ifdef __APPLE__
#include <sys/timeb.h>
#endif

ulongint getTickCount()
{
#ifdef __APPLE__
    timeb tb;
    ftime(&tb);
    return tb.millitm + (tb.time & 0xfffff) * 1000;
#else
    struct timespec ts;

    if (clock_gettime(CLOCK_MONOTONIC, &ts))
    {
        return 0;
    }
    return (ts.tv_sec * 1000) + ts.tv_nsec / 1000000L;
#endif
}

**Comment by dk547** [comment]
Yep, this code seems OK. 

One more thing:

library not found for -lrt

To link the library I removed -lrt from CMakeLists.txt

**Comment by YasserAsmi** [comment]
fixed
