### ISSUE TITLE
Need to test/adjust CMake project for windows/mac.

### ISSUE THREAD

**Issue by YasserAsmi** [YasserAsmi/jvar#2]
The code doesn't have dependancies on any platform specifics.  But I have only tested on Linux so far.

**Comment by jbmonroe** [comment]
Actually, it does.

    #include <sys/wait.h>

That header isn't available in Visual C++ (under Studio 2012, at least).

The function strcasecmp isn't portable.  The POSIX-standard name is _stricmp.  There are a few other interesting warnings.

1>\jvar\include\arr.h(689): warning C4521: 'jvar::ObjArray<T>' : multiple copy constructors specified

**Comment by YasserAsmi** [comment]
Thanks.  I will take a look and fix these issues.  I have Visual Studio 2012 on Windows.  I will make it work with that.

**Comment by YasserAsmi** [comment]
Fixed and tested the build on Windows using Visual Studio 2012.  CMake correctly generates the Visual Studio project.  The library builds fine. Reworked the ex_jsonparse using Windows FindFirstFile.
