### ISSUE TITLE
Cygwin: strptime was not declared

### ISSUE THREAD

**Issue by andrei-markeev** [YasserAsmi/jvar#20]
Hi,

When including jvar.h to an application and building with -std=c++11 or -std=c++14, there's an error under Cygwin:

```console
$ g++ test.cpp -o test -std=c++11
In file included from /usr/local/include/jvar/jvar.h:11:0,
                 from test.cpp:1:
/usr/local/include/jvar/util.h: In member function ‘bool jvar::Date::parse(const char*, const char*)’:
/usr/local/include/jvar/util.h:432:65: error: ‘strptime’ was not declared in this scope
         return (strptime(str, fmt == NULL ? stdFmt() : fmt, this) != NULL);
```

(test.cpp has `#include <jvar/jvar.h>` and empty main and that's it)

Build succeeds without -std or with -std=gnu++11/-std=gnu++14.

**Comment by YasserAsmi** [comment]
Weird... It has something to do with __STRICT_ANSI__

**Comment by YasserAsmi** [comment]
I have a fix... Can you please review it and see it looks ok?

diff --git a/include/util.h b/include/util.h
index 7134538..2360973 100644
--- a/include/util.h
+++ b/include/util.h
@@ -16,6 +16,11 @@

 #endif

+#ifdef __CYGWIN__
+// This define blocks some functions such as strptime() that are required
+#undef __STRICT_ANSI__
+#endif
+
 #include <stdio.h>
 #include <assert.h>
 #include <stdlib.h>
@@ -31,6 +36,7 @@
 #endif
 //#include <stdint.h>

+
 #include <string>

 #ifndef NDEBUG

**Comment by andrei-markeev** [comment]
Hi! Yes it works, thanks!
